### ISSUE TITLE
Multi-monitor screenshots break the homepage in Firefox

### ISSUE THREAD

**Issue by dmpayton** [qtile/qtile.org#3]
![qtile-homepage-broke](https://cloud.githubusercontent.com/assets/149918/3961405/9b622982-2753-11e4-9626-8d9542e104b6.jpg)

Likely related to this:
https://stackoverflow.com/questions/14550356/image-mysteriously-ignoring-max-width-in-firefox-ie

**Comment by tych0** [comment]
This seems fixed to me with the rework, please reopen if not.
