### ISSUE TITLE
Issue with scrolling over the example.

### ISSUE THREAD

**Issue by dgnsrekt** [qtile/qtile.org#36]
Current:
![image](https://user-images.githubusercontent.com/25717871/145676254-ebc9402f-27b4-4ebb-b176-ee62df538529.png)
![image](https://user-images.githubusercontent.com/25717871/145676288-fe0e3cfb-b559-4f5e-b7fe-3931840c7c08.png)

Probably what it should look like.
![image](https://user-images.githubusercontent.com/25717871/145676340-16f16517-4e95-46b6-af01-eef3e71a18fc.png)
![image](https://user-images.githubusercontent.com/25717871/145676349-1836ca15-737a-4538-a79c-69bc1bd145fa.png)

**Comment by tych0** [comment]
Thanks for the report! Any chance you can send a patch for this issue?

**Comment by dgnsrekt** [comment]
![image](https://user-images.githubusercontent.com/25717871/145687984-b6768236-1a3c-46ab-82dd-197dab8a134a.png)
I'm sorry. It appears I didn't notice the expansion button at the top. There is no issue.
