### ISSUE TITLE
Wrong display

### ISSUE THREAD

**Issue by k4leg** [qtile/qtile.org#39]
See (main page, config example):
<img width="425" alt="1" src="https://user-images.githubusercontent.com/39882583/155855833-cb2bcafb-af03-413c-a0bf-b4af9f737eeb.png">

Single quote becomes `&#x27;`.

Additional info: Firefox 97.0.1-1 (Arch Linux), JetBrains Mono font.

**Comment by m-col** [comment]
Thanks for the report. It looks like a bunch of things are broken in that snippet. @elParaguayo you were playing around with redoing the website right? I wonder if we could add something to qtile's CI to raise an issue here (or even a PR) if the default config is changed, so it can be kept up to date there.

**Comment by elParaguayo** [comment]
And, yes, I think we can trigger builds of the docs when we push a new release.

**Comment by tych0** [comment]
I fixed this via https://github.com/qtile/qtile.org/commit/c7f41f9afadc6ddd64fc3606fe3f8022b3440d0c
