### ISSUE TITLE
documentaion website is down

### ISSUE THREAD

**Issue by Freemason-12** [qtile/qtile.org#48]
when I go into docs.qtile.org it's just down, every other site is working

**Comment by daetalys** [comment]
You should be seeing a "DNS_PROBE_POSSIBLE" error. If so, they're working on it. Shifts like these do unfortunately take a great deal of patience. This issue has already been addressed in https://github.com/qtile/qtile.org/issues/41#issuecomment-1575508730_ I also came here to open an issue about it, only to find that it is already being addressed.

**Comment by rockhazard** [comment]
I can't vouch for its accuracy or how current it is, but it looks like a copy of the Qtile docs are here: [https://qtile.readthedocs.io](https://qtile.readthedocs.io)
This may be a decent interim solution until the official docs are back up.

**Comment by ramnes** [comment]
Fixed apparently
